"""Fixture loader.

The JSON files here are generated by `build_fixtures.py`, which drives the real
`app.main.route_message`. Every belief number in them came out of the real
`BeliefState`; nothing is hand-written. See that module's docstring.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from app.state import Deal

HERE = Path(__file__).resolve().parent

CAMRY = "deal_camry"       # NEGOTIATING, 4 turns, turn 3 is a bluff
CIVIC = "deal_civic"       # AWAITING_RESEARCH — snapshot is None, research is None
FRESH = "deal_fresh"       # AWAITING_LINK — every optional field null
F150 = "deal_f150"         # CLOSED, under ask
TACOMA = "deal_tacoma"     # WALKED, above fair value

ALL = (CAMRY, CIVIC, F150, TACOMA, FRESH)


@lru_cache(maxsize=None)
def _raw(name: str) -> str:
    return (HERE / f"{name}.json").read_text()


def load(name: str) -> Deal:
    """A fresh `Deal` every call — tests mutate them."""
    return Deal(**json.loads(_raw(name)))


def load_all() -> list[Deal]:
    return [load(n) for n in ALL]


__all__ = ["load", "load_all", "ALL", "CAMRY", "CIVIC", "FRESH", "F150", "TACOMA"]
