/**
 * Generate RSA Key Pair for External JWT Authentication
 *
 * Run this script once to generate an RSA-256 key pair for signing JWTs.
 * Copy the output into your .env.local file.
 *
 * Usage:
 *   npx tsx scripts/generate-keypair.ts
 *
 * @see https://www.dynamic.xyz/docs/javascript/external-auth/third-party-auth-setup
 */

import { generateKeyPair, exportJWK } from "jose";

async function main() {
  const kid = `demo-key-${Date.now()}`;

  console.log("Generating RSA-256 key pair...\n");

  const { publicKey, privateKey } = await generateKeyPair("RS256", {
    extractable: true,
  });

  const publicJwk = await exportJWK(publicKey);
  const privateJwk = await exportJWK(privateKey);

  // Add key metadata
  publicJwk.kid = kid;
  publicJwk.use = "sig";
  publicJwk.alg = "RS256";

  privateJwk.kid = kid;
  privateJwk.use = "sig";
  privateJwk.alg = "RS256";

  console.log("Add the following to your .env.local:\n");
  console.log(
    "# ─── External JWT Auth (generated by scripts/generate-keypair.ts) ───",
  );
  console.log(`JWT_PROVIDER_KID=${kid}`);
  console.log(`JWT_PROVIDER_ISSUER=https://demo-jwt-provider.example.com`);
  console.log(`JWT_PROVIDER_PUBLIC_KEY='${JSON.stringify(publicJwk)}'`);
  console.log(`JWT_PROVIDER_PRIVATE_KEY='${JSON.stringify(privateJwk)}'`);
}

main().catch(console.error);
